### ISSUE TITLE
Change API URL to api.track.toggl.com because otherwise the wrapper will stop working after June 30th, 2021

### ISSUE THREAD

**Issue by stranljip** [aarose/togglwrapper#31]
Toggl is dropping support for API calls to www.toggl.com after June 30th:

> Hi there, 
> 
> We are reaching out because we detected your Toggl Track API usage coming to the www.toggl.com(or toggl.com) domain. 
> 
> If you (or your company) have developed a custom integration, we want to remind you that the usage of www.toggl.com (or toggl.com) domains for the API will be dropped after 'June 30th 2021'. 
> 
> We encourage you to perform the switch to api.track.toggl.com as soon as possible in order to prevent disruption. Please check the official API Documentation for any extra info. 

The API URL is built into the extension so that a new release should be made. There is already a related PR #27 

Since there are only a little less than two weeks to go, I would greatly appreciate if the PR could be approved and merged and a new release could be made.

**Comment by stranljip** [comment]
I merged the changes of the mentioned PR from @charlesthomas in our fork (https://github.com/DisyInformationssysteme/togglwrapper). You are welcome to install it from there with
```
python -m pip install git+https://github.com/DisyInformationssysteme/togglwrapper.git
```

I am not planning to maintain our fork longer than needed, so I hope that it will be integrated here in the near future.

**Comment by aarose** [comment]
Closed by https://github.com/aarose/togglwrapper/pull/27
